var LANGUAGES =
    [
    {bcp: "ar-SA", language: "Arabic", country: "Saudi Arabia"},
    {bcp: "ar-BH", language: "Arabic", country: "Bahrain"},
    {bcp: "ar-EG", language: "Arabic", country: "Egypt"},
    {bcp: "ar-KW", language: "Arabic", country: "Kuwait"},
    {bcp: "ar-QA", language: "Arabic", country: "Qatar"},
    {bcp: "ar-AE", language: "Arabic", country: "the United Arab Emirates"},
    {bcp: "cs-CZ", language: "Czech", country: "Czech Republic"},
    {bcp: "da-DK", language: "Danish", country: "Denmark"},
    {bcp: "de-DE", language: "German", country: "Germany"},
    {bcp: "en-AU", language: "English", country: "Australia"},
    {bcp: "en-GB", language: "English", country: "the United Kingdom"},
    {bcp: "en-IE", language: "English", country: "Ireland"},
    {bcp: "en-US", language: "English", country: "America"},
    {bcp: "en-ZA", language: "English", country: "South Africa"},
    {bcp: "es-ES", language: "Spanish", country: "Spain"},
    {bcp: "es-MX", language: "Spanish", country: "Mexico"},
    {bcp: "fi-FI", language: "Finnish", country: "Finland"},
    {bcp: "fr-CA", language: "French", country: "Canada"},
    {bcp: "fr-FR", language: "French", country: "France"},
    {bcp: "fr-CH", language: "French", country: "Switzerland"},
    {bcp: "el-GR", language: "Greek", country: "Greece"},
    {bcp: "he-IL", language: "Hebrew", country: "Israel"},
    {bcp: "hi-IN", language: "Hindi", country: "India"},
    {bcp: "hu-HU", language: "Hungarian", country: "Hungary"},
    {bcp: "id-ID", language: "Indonesian", country: "Indonesia"},
    {bcp: "it-IT", language: "Italian", country: "Italy"},
    {bcp: "ja-JP", language: "Japanese", country: "Japan"},
    {bcp: "ko-KR", language: "Korean", country: "South Korea"},
    {bcp: "ms-MY", language: "Malaysian", country: "Malaysia"},
    {bcp: "nl-BE", language: "Dutch", country: "Belgium"},
    {bcp: "nl-NL", language: "Dutch", country: "Netherlands"},
    {bcp: "nb-NO", language: "Norwegian", country: "Norway"},
    {bcp: "pl-PL", language: "Polish", country: "Poland"},
    {bcp: "pt-BR", language: "Portuguese", country: "Brazil"},
    {bcp: "pt-PT", language: "Portuguese", country: "Portugal"},
    {bcp: "ro-RO", language: "Romanian", country: "Romania"},
    {bcp: "ru-RU", language: "Russian", country: "Russia"},
    {bcp: "sk-SK", language: "Slovak", country: "Slovakia"},
    {bcp: "sv-SE", language: "Swedish", country: "Sweden"},
    {bcp: "th-TH", language: "Thai", country: "Thailand"},
    {bcp: "tr-TR", language: "Turkish", country: "Turkey"},
    {bcp: "vi-VN", language: "Vietnamese", country: "Vietnam"},
    {bcp: "zh-CN", language: "Chinese", country: "China"},
    {bcp: "zh-HK", language: "Chinese", country: "Hong Kong"},
    {bcp: "zh-TW", language: "Chinese", country: "Taiwan"}
];
